const data = [
  {
    name: { username: "Alice", handle: "@alice", avatar: "https://i.pravatar.cc/40?img=1" },
    age: 29,
    status: "Working",
    role: "Product Manager",
    email: "alice@company.com",
    teams: ["Design", "Product", "Development"],
  },
  {
    name: { username: "Bob", handle: "@bob", avatar: "https://i.pravatar.cc/40?img=2" },
    age: 35,
    status: "Working",
    role: "Developer",
    email: "bob@company.com",
    teams: ["Engineering", "Development"],
  },
  {
    name: { username: "Charlie", handle: "@charlie", avatar: "https://i.pravatar.cc/40?img=3" },
    age: 27,
    status: "Working",
    role: "Designer",
    email: "charlie@company.com",
    teams: ["Design", "UX"],
  },
  {
    name: { username: "David", handle: "@david", avatar: "https://i.pravatar.cc/40?img=4" },
    age: 32,
    status: "Working",
    role: "QA Engineer",
    email: "david@company.com",
    teams: ["Testing", "Development"],
  },
  {
    name: { username: "Emma", handle: "@emma", avatar: "https://i.pravatar.cc/40?img=5" },
    age: 28,
    status: "Working",
    role: "Data Scientist",
    email: "emma@company.com",
    teams: ["Data", "AI"],
  },
  {
    name: { username: "Frank", handle: "@frank", avatar: "https://i.pravatar.cc/40?img=6" },
    age: 40,
    status: "Working",
    role: "Marketing Manager",
    email: "frank@company.com",
    teams: ["Marketing", "Sales"],
  },
  {
    name: { username: "Grace", handle: "@grace", avatar: "https://i.pravatar.cc/40?img=7" },
    age: 30,
    status: "Working",
    role: "HR Manager",
    email: "grace@company.com",
    teams: ["HR", "Recruitment"],
  },
  {
    name: { username: "Henry", handle: "@henry", avatar: "https://i.pravatar.cc/40?img=8" },
    age: 31,
    status: "Working",
    role: "Software Engineer",
    email: "henry@company.com",
    teams: ["Development", "Engineering"],
  },
  {
    name: { username: "Isabel", handle: "@isabel", avatar: "https://i.pravatar.cc/40?img=9" },
    age: 26,
    status: "Working",
    role: "UI/UX Designer",
    email: "isabel@company.com",
    teams: ["Design", "Product"],
  },
  {
    name: { username: "Jack", handle: "@jack", avatar: "https://i.pravatar.cc/40?img=10" },
    age: 33,
    status: "Working",
    role: "Backend Developer",
    email: "jack@company.com",
    teams: ["Backend", "Development"],
  },
  {
    name: { username: "Kate", handle: "@kate", avatar: "https://i.pravatar.cc/40?img=11" },
    age: 29,
    status: "Working",
    role: "DevOps Engineer",
    email: "kate@company.com",
    teams: ["DevOps", "Infrastructure"],
  },
  {
    name: { username: "Leo", handle: "@leo", avatar: "https://i.pravatar.cc/40?img=12" },
    age: 34,
    status: "Working",
    role: "Scrum Master",
    email: "leo@company.com",
    teams: ["Agile", "Product"],
  },
  {
    name: { username: "Mia", handle: "@mia", avatar: "https://i.pravatar.cc/40?img=13" },
    age: 25,
    status: "Working",
    role: "Data Analyst",
    email: "mia@company.com",
    teams: ["Analytics", "Data"],
  },
  {
    name: { username: "Noah", handle: "@noah", avatar: "https://i.pravatar.cc/40?img=14" },
    age: 37,
    status: "Working",
    role: "Cybersecurity Engineer",
    email: "noah@company.com",
    teams: ["Security", "IT"],
  },
  {
    name: { username: "Olivia", handle: "@olivia", avatar: "https://i.pravatar.cc/40?img=15" },
    age: 28,
    status: "Working",
    role: "Frontend Developer",
    email: "olivia@company.com",
    teams: ["Frontend", "Development"],
  },
  {
    name: { username: "Paul", handle: "@paul", avatar: "https://i.pravatar.cc/40?img=16" },
    age: 42,
    status: "Working",
    role: "Technical Writer",
    email: "paul@company.com",
    teams: ["Documentation", "Product"],
  },
  {
    name: { username: "Quinn", handle: "@quinn", avatar: "https://i.pravatar.cc/40?img=17" },
    age: 36,
    status: "Working",
    role: "Cloud Architect",
    email: "quinn@company.com",
    teams: ["Cloud", "Infrastructure"],
  },
  {
    name: { username: "Rachel", handle: "@rachel", avatar: "https://i.pravatar.cc/40?img=18" },
    age: 29,
    status: "Working",
    role: "Machine Learning Engineer",
    email: "rachel@company.com",
    teams: ["AI", "ML"],
  },
  {
    name: { username: "Steve", handle: "@steve", avatar: "https://i.pravatar.cc/40?img=19" },
    age: 35,
    status: "Working",
    role: "Game Developer",
    email: "steve@company.com",
    teams: ["Game Dev", "Product"],
  },
  {
    name: { username: "Tina", handle: "@tina", avatar: "https://i.pravatar.cc/40?img=20" },
    age: 27,
    status: "Working",
    role: "Support Engineer",
    email: "tina@company.com",
    teams: ["Support", "IT"],
  },
  {
    name: { username: "Victor", handle: "@victor", avatar: "https://i.pravatar.cc/40?img=21" },
    age: 31,
    status: "Working",
    role: "Developer",
    email: "victor@company.com",
    teams: ["Development", "Engineering"],
  },
  {
    name: { username: "Wendy", handle: "@wendy", avatar: "https://i.pravatar.cc/40?img=22" },
    age: 30,
    status: "Working",
    role: "Data Scientist",
    email: "wendy@company.com",
    teams: ["AI", "Data"],
  },
];

export default data;
